apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: existing-roadrunner-dotnet-basic
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:41124779e977482673f47ad0c285a415ac9e853d@sha256:3b4df81f33e632ac06ad295c04b4463d210ea8ce9a453cb4ea7b169cc72908ee
        name: container-image  
